import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
const Home = () => {
    return (React.createElement("div", { className: styles.container },
        React.createElement(Head, null,
            React.createElement("title", null, "Create Next App"),
            React.createElement("meta", { name: "description", content: "Generated by create next app" }),
            React.createElement("link", { rel: "icon", href: "/favicon.ico" })),
        React.createElement("main", { className: styles.main },
            React.createElement("h1", { className: styles.title },
                "Welcome to ",
                React.createElement("a", { href: "https://nextjs.org" }, "Next.js!")),
            React.createElement("p", { className: styles.description },
                "Get started by editing",
                ' ',
                React.createElement("code", { className: styles.code }, "pages/index.tsx")),
            React.createElement("div", { className: styles.grid },
                React.createElement("a", { href: "https://nextjs.org/docs", className: styles.card },
                    React.createElement("h2", null, "Documentation \u2192"),
                    React.createElement("p", null, "Find in-depth information about Next.js features and API.")),
                React.createElement("a", { href: "https://nextjs.org/learn", className: styles.card },
                    React.createElement("h2", null, "Learn \u2192"),
                    React.createElement("p", null, "Learn about Next.js in an interactive course with quizzes!")),
                React.createElement("a", { href: "https://github.com/vercel/next.js/tree/master/examples", className: styles.card },
                    React.createElement("h2", null, "Examples \u2192"),
                    React.createElement("p", null, "Discover and deploy boilerplate example Next.js projects.")),
                React.createElement("a", { href: "https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app", className: styles.card },
                    React.createElement("h2", null, "Deploy \u2192"),
                    React.createElement("p", null, "Instantly deploy your Next.js site to a public URL with Vercel.")))),
        React.createElement("footer", { className: styles.footer },
            React.createElement("a", { href: "https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app", target: "_blank", rel: "noopener noreferrer" },
                "Powered by",
                ' ',
                React.createElement("span", { className: styles.logo },
                    React.createElement(Image, { src: "/vercel.svg", alt: "Vercel Logo", width: 72, height: 16 }))))));
};
export default Home;
//# sourceMappingURL=index.js.map