//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolidApp.Shared.Localizations.Resources
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource
    {
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolidApp.Shared.Localizations.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
                
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string UserActionEnum_Cancel
        {
            get
            {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string UserActionEnum_Create
        {
            get
            {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string MessageStateEnum_Read
        {
            get
            {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UserActionEnum_Update
        {
            get
            {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string UserActionEnum_Delete
        {
            get
            {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Like.
        /// </summary>
        public static string UserReactionEnum_Like
        {
            get
            {
                return ResourceManager.GetString("Like", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Dislike.
        /// </summary>
        public static string UserReactionEnum_Dislike
        {
            get
            {
                return ResourceManager.GetString("Dislike", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Laugh.
        /// </summary>
        public static string UserReactionEnum_Laugh
        {
            get
            {
                return ResourceManager.GetString("Laugh", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Shock.
        /// </summary>
        public static string UserActionEnum_Shock
        {
            get
            {
                return ResourceManager.GetString("Shock", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Smile.
        /// </summary>
        public static string UserActionEnum_Smile
        {
            get
            {
                return ResourceManager.GetString("Smile", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string AddressEnum_None
        {
            get
            {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Leader.
        /// </summary>
        public static string UserGroupRoleEnum_Leader
        {
            get
            {
                return ResourceManager.GetString("Leader", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Vice leader.
        /// </summary>
        public static string UserGroupRoleEnum_ViceLeader
        {
            get
            {
                return ResourceManager.GetString("Vice leader", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Maintainer.
        /// </summary>
        public static string UserGroupRoleEnum_Maintainer
        {
            get
            {
                return ResourceManager.GetString("Maintainer", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Hooray.
        /// </summary>
        public static string UserReactionEnum_Hooray
        {
            get
            {
                return ResourceManager.GetString("Hooray", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Heart.
        /// </summary>
        public static string UserReactionEnum_Heart
        {
            get
            {
                return ResourceManager.GetString("Heart", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Confused.
        /// </summary>
        public static string UserReactionEnum_Confused
        {
            get
            {
                return ResourceManager.GetString("Confused", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Shocked.
        /// </summary>
        public static string MessageStateEnum_Shocked
        {
            get
            {
                return ResourceManager.GetString("Shocked", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string QuestionEnum_Select
        {
            get
            {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string SurveyQuestionAnswerEnum_Text
        {
            get
            {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Check box.
        /// </summary>
        public static string QuestionEnum_CheckBox
        {
            get
            {
                return ResourceManager.GetString("Check box", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Javascript.
        /// </summary>
        public static string ClientWebProgrammingLanguageEnum_Javascript
        {
            get
            {
                return ResourceManager.GetString("Javascript", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Typescript.
        /// </summary>
        public static string ClientWebProgrammingLanguageEnum_Typescript
        {
            get
            {
                return ResourceManager.GetString("Typescript", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to C sharp.
        /// </summary>
        public static string ClientWebProgrammingLanguageEnum_CSharp
        {
            get
            {
                return ResourceManager.GetString("C sharp", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Python.
        /// </summary>
        public static string ServerProgrammingLanguageEnum_Python
        {
            get
            {
                return ResourceManager.GetString("Python", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        public static string SurveyQuestionAnswerEnum_Any
        {
            get
            {
                return ResourceManager.GetString("Any", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Numeric.
        /// </summary>
        public static string SurveyQuestionAnswerEnum_Numeric
        {
            get
            {
                return ResourceManager.GetString("Numeric", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Html.
        /// </summary>
        public static string SurveyQuestionAnswerEnum_Html
        {
            get
            {
                return ResourceManager.GetString("Html", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Json.
        /// </summary>
        public static string SurveyQuestionAnswerEnum_Json
        {
            get
            {
                return ResourceManager.GetString("Json", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string ViewableByEnum_Family
        {
            get
            {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Friend.
        /// </summary>
        public static string ViewableByEnum_Friend
        {
            get
            {
                return ResourceManager.GetString("Friend", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string ViewableByEnum_Connection
        {
            get
            {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Everyone.
        /// </summary>
        public static string ViewableByEnum_Everyone
        {
            get
            {
                return ResourceManager.GetString("Everyone", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string ViewableByEnum_Selected
        {
            get
            {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Dating.
        /// </summary>
        public static string RelationshipEnum_Dating
        {
            get
            {
                return ResourceManager.GetString("Dating", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Married.
        /// </summary>
        public static string RelationshipEnum_Married
        {
            get
            {
                return ResourceManager.GetString("Married", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Firtilization.
        /// </summary>
        public static string GerminalStageEnum_Firtilization
        {
            get
            {
                return ResourceManager.GetString("Firtilization", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Cleavage.
        /// </summary>
        public static string PrenatalStageEnum_Germinal_Day2
        {
            get
            {
                return ResourceManager.GetString("Cleavage", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Blastulation.
        /// </summary>
        public static string GerminalStageEnum_Blastulation
        {
            get
            {
                return ResourceManager.GetString("Blastulation", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Implantation.
        /// </summary>
        public static string GerminalStageEnum_Implantation
        {
            get
            {
                return ResourceManager.GetString("Implantation", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Firtilized.
        /// </summary>
        public static string PrenatalStageEnum_Germinal_Day1
        {
            get
            {
                return ResourceManager.GetString("Firtilized", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Morula.
        /// </summary>
        public static string PrenatalStageEnum_Germinal_Day4
        {
            get
            {
                return ResourceManager.GetString("Morula", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Blastocyst.
        /// </summary>
        public static string PrenatalStageEnum_Germinal_Day5
        {
            get
            {
                return ResourceManager.GetString("Blastocyst", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Blastocyst Implants in the endometrium of the uterus..
        /// </summary>
        public static string PrenatalStageEnum_Germinal_Day8
        {
            get
            {
                return ResourceManager.GetString("Blastocyst Implants in the endometrium of the uterus.", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Embryonic Disc.
        /// </summary>
        public static string PrenatalStageEnum_EmbryonicStage_Day9
        {
            get
            {
                return ResourceManager.GetString("Embryonic Disc", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Gastrulation.
        /// </summary>
        public static string PrenatalStageEnum_EmbryonicStage_Week2
        {
            get
            {
                return ResourceManager.GetString("Gastrulation", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Neurulation.
        /// </summary>
        public static string PrenatalStageEnum_EmbryonicStage_Week3
        {
            get
            {
                return ResourceManager.GetString("Neurulation", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Organogenesis: C shape.
        /// </summary>
        public static string PrenatalStageEnum_EmbryonicStage_Week5
        {
            get
            {
                return ResourceManager.GetString("Organogenesis: C shape", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Organogenesis: Eyes and nose develop, stomach start to develop..
        /// </summary>
        public static string PrenatalStageEnum_EmbryonicStage_Week6
        {
            get
            {
                return ResourceManager.GetString("Organogenesis: Eyes and nose develop, stomach start to develop.", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Organogenesis: Lung begins to form..
        /// </summary>
        public static string PrenatalStageEnum_EmbryonicStage_Week7
        {
            get
            {
                return ResourceManager.GetString("Organogenesis: Lung begins to form.", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Organogenesis: Nipples and hair follicles begins to develop..
        /// </summary>
        public static string PrenatalStageEnum_EmbryonicStage_Week8
        {
            get
            {
                return ResourceManager.GetString("Organogenesis: Nipples and hair follicles begins to develop.", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Fetal Stage begins..
        /// </summary>
        public static string PrenatalStageEnum_FetalStage_Week9
        {
            get
            {
                return ResourceManager.GetString("Fetal Stage begins.", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Sex organs differentiate..
        /// </summary>
        public static string PrenatalStageEnum_FetalStage_Week12
        {
            get
            {
                return ResourceManager.GetString("Sex organs differentiate.", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Fingers and toes develop..
        /// </summary>
        public static string PrenatalStageEnum_FetalStage_Week16
        {
            get
            {
                return ResourceManager.GetString("Fingers and toes develop.", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Hearing begins.
        /// </summary>
        public static string PrenatalStageEnum_FetalStage_Week20
        {
            get
            {
                return ResourceManager.GetString("Hearing begins", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Lungs begin to develop..
        /// </summary>
        public static string PrenatalStageEnum_FetalStage_Week24
        {
            get
            {
                return ResourceManager.GetString("Lungs begin to develop.", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Brains grow rapidly..
        /// </summary>
        public static string PrenatalStageEnum_FetalStage_Week28
        {
            get
            {
                return ResourceManager.GetString("Brains grow rapidly.", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Bones fully develop..
        /// </summary>
        public static string PrenatalStageEnum_FetalStage_Week32
        {
            get
            {
                return ResourceManager.GetString("Bones fully develop.", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Muscles fully develop..
        /// </summary>
        public static string PrenatalStageEnum_FetalStage_Week36
        {
            get
            {
                return ResourceManager.GetString("Muscles fully develop.", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Full-term development..
        /// </summary>
        public static string PrenatalStageEnum_FetalStage_Week40
        {
            get
            {
                return ResourceManager.GetString("Full-term development.", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Liked.
        /// </summary>
        public static string MessageStateEnum_Liked
        {
            get
            {
                return ResourceManager.GetString("Liked", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Disliked.
        /// </summary>
        public static string MessageStateEnum_Disliked
        {
            get
            {
                return ResourceManager.GetString("Disliked", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string NotificationIconEnum_Alert
        {
            get
            {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Urgent.
        /// </summary>
        public static string NotificationIconEnum_Urgent
        {
            get
            {
                return ResourceManager.GetString("Urgent", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string OnlineStatusEnum_Online
        {
            get
            {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string OnlineStatusEnum_Offline
        {
            get
            {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string JobCategoryEnum_Web
        {
            get
            {
                return ResourceManager.GetString("Web", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Software.
        /// </summary>
        public static string JobCategoryEnum_Software
        {
            get
            {
                return ResourceManager.GetString("Software", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Architecture.
        /// </summary>
        public static string JobCategoryEnum_Architecture
        {
            get
            {
                return ResourceManager.GetString("Architecture", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Job applicant.
        /// </summary>
        public static string JobRoleEnum_JobApplicant
        {
            get
            {
                return ResourceManager.GetString("Job applicant", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Job employee.
        /// </summary>
        public static string JobRoleEnum_JobEmployee
        {
            get
            {
                return ResourceManager.GetString("Job employee", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Job recruiter.
        /// </summary>
        public static string JobRoleEnum_JobRecruiter
        {
            get
            {
                return ResourceManager.GetString("Job recruiter", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Software engineer.
        /// </summary>
        public static string JobTitleEnum_SoftwareEngineer
        {
            get
            {
                return ResourceManager.GetString("Software engineer", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Web designer.
        /// </summary>
        public static string JobTitleEnum_WebDesigner
        {
            get
            {
                return ResourceManager.GetString("Web designer", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Web engineer.
        /// </summary>
        public static string JobTitleEnum_WebEngineer
        {
            get
            {
                return ResourceManager.GetString("Web engineer", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Roommate.
        /// </summary>
        public static string HouseholdRoleEnum_Roommate
        {
            get
            {
                return ResourceManager.GetString("Roommate", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Dependent.
        /// </summary>
        public static string HouseholdRoleEnum_Dependent
        {
            get
            {
                return ResourceManager.GetString("Dependent", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string GenderEnum_Male
        {
            get
            {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string GenderEnum_Female
        {
            get
            {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Mother.
        /// </summary>
        public static string FamilyRelationEnum_Mother
        {
            get
            {
                return ResourceManager.GetString("Mother", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Father.
        /// </summary>
        public static string FamilyRelationEnum_Father
        {
            get
            {
                return ResourceManager.GetString("Father", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Son.
        /// </summary>
        public static string FamilyRelationEnum_Son
        {
            get
            {
                return ResourceManager.GetString("Son", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Daughter.
        /// </summary>
        public static string FamilyRelationEnum_Daughter
        {
            get
            {
                return ResourceManager.GetString("Daughter", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Brother.
        /// </summary>
        public static string FamilyRelationEnum_Brother
        {
            get
            {
                return ResourceManager.GetString("Brother", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Sister.
        /// </summary>
        public static string FamilyRelationEnum_Sister
        {
            get
            {
                return ResourceManager.GetString("Sister", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Uncle.
        /// </summary>
        public static string FamilyRelationEnum_Uncle
        {
            get
            {
                return ResourceManager.GetString("Uncle", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Aunt.
        /// </summary>
        public static string FamilyRelationEnum_Aunt
        {
            get
            {
                return ResourceManager.GetString("Aunt", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Nephew.
        /// </summary>
        public static string FamilyRelationEnum_Nephew
        {
            get
            {
                return ResourceManager.GetString("Nephew", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Niece.
        /// </summary>
        public static string FamilyRelationEnum_Niece
        {
            get
            {
                return ResourceManager.GetString("Niece", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Cousin (Female).
        /// </summary>
        public static string FamilyRelationEnum_CousinFemale
        {
            get
            {
                return ResourceManager.GetString("Cousin (Female)", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Cousin (Male).
        /// </summary>
        public static string FamilyRelationEnum_CousinMale
        {
            get
            {
                return ResourceManager.GetString("Cousin (Male)", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Grandmother.
        /// </summary>
        public static string FamilyRelationEnum_Grandmother
        {
            get
            {
                return ResourceManager.GetString("Grandmother", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Grandfather.
        /// </summary>
        public static string FamilyRelationEnum_Grandfather
        {
            get
            {
                return ResourceManager.GetString("Grandfather", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Granddaughter.
        /// </summary>
        public static string FamilyRelationEnum_Granddaughter
        {
            get
            {
                return ResourceManager.GetString("Granddaughter", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Grandson.
        /// </summary>
        public static string FamilyRelationEnum_Grandson
        {
            get
            {
                return ResourceManager.GetString("Grandson", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Stepsister.
        /// </summary>
        public static string FamilyRelationEnum_Stepsister
        {
            get
            {
                return ResourceManager.GetString("Stepsister", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Stepbrother.
        /// </summary>
        public static string FamilyRelationEnum_Stepbrother
        {
            get
            {
                return ResourceManager.GetString("Stepbrother", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Stepmother.
        /// </summary>
        public static string FamilyRelationEnum_Stepmother
        {
            get
            {
                return ResourceManager.GetString("Stepmother", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Stepfather.
        /// </summary>
        public static string FamilyRelationEnum_Stepfather
        {
            get
            {
                return ResourceManager.GetString("Stepfather", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Stepdaughter.
        /// </summary>
        public static string FamilyRelationEnum_Stepdaughter
        {
            get
            {
                return ResourceManager.GetString("Stepdaughter", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Stepson.
        /// </summary>
        public static string FamilyRelationEnum_Stepson
        {
            get
            {
                return ResourceManager.GetString("Stepson", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Sister-in-law.
        /// </summary>
        public static string FamilyRelationEnum_SisterInLaw
        {
            get
            {
                return ResourceManager.GetString("Sister-in-law", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Brother-in-law.
        /// </summary>
        public static string FamilyRelationEnum_BrotherInLaw
        {
            get
            {
                return ResourceManager.GetString("Brother-in-law", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Mother-in-law.
        /// </summary>
        public static string FamilyRelationEnum_MotherInLaw
        {
            get
            {
                return ResourceManager.GetString("Mother-in-law", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Father-in-law.
        /// </summary>
        public static string FamilyRelationEnum_FatherInLaw
        {
            get
            {
                return ResourceManager.GetString("Father-in-law", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Daughter-in-law.
        /// </summary>
        public static string FamilyRelationEnum_DaughterInLaw
        {
            get
            {
                return ResourceManager.GetString("Daughter-in-law", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Son in law.
        /// </summary>
        public static string FamilyRelationEnum_SonInLaw
        {
            get
            {
                return ResourceManager.GetString("Son in law", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Sibling (Gender neutral).
        /// </summary>
        public static string FamilyRelationEnum_Sibling_GenderNeutral
        {
            get
            {
                return ResourceManager.GetString("Sibling (Gender neutral)", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Parent (Gender neutral).
        /// </summary>
        public static string FamilyRelationEnum_Parent_GenderNeutral
        {
            get
            {
                return ResourceManager.GetString("Parent (Gender neutral)", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Sibling of parent (Gender neutral).
        /// </summary>
        public static string FamilyRelationEnum_SiblingOfParent_GenderNeutral
        {
            get
            {
                return ResourceManager.GetString("Sibling of parent (Gender neutral)", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Child of sibling (Gender neutral).
        /// </summary>
        public static string FamilyRelationEnum_ChildOfSibling_GenderNeutral
        {
            get
            {
                return ResourceManager.GetString("Child of sibling (Gender neutral)", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Child (Gender neutral).
        /// </summary>
        public static string FamilyRelationEnum_Child_GenderNeutral
        {
            get
            {
                return ResourceManager.GetString("Child (Gender neutral)", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Cousin (Gender neutral).
        /// </summary>
        public static string FamilyRelationEnum_Cousin_GenderNeutral
        {
            get
            {
                return ResourceManager.GetString("Cousin (Gender neutral)", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Child-in-law (Gender neutral).
        /// </summary>
        public static string FamilyRelationEnum_ChildInLaw_GenderNeutral
        {
            get
            {
                return ResourceManager.GetString("Child-in-law (Gender neutral)", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Parent-in-law (Gender neutral).
        /// </summary>
        public static string FamilyRelationEnum_ParentInLaw_GenderNeutral
        {
            get
            {
                return ResourceManager.GetString("Parent-in-law (Gender neutral)", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Sibling-in-law (Gender neutral).
        /// </summary>
        public static string FamilyRelationEnum_SiblingInLaw_GenderNeutral
        {
            get
            {
                return ResourceManager.GetString("Sibling-in-law (Gender neutral)", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Step parent (Gender neutral).
        /// </summary>
        public static string FamilyRelationEnum_StepParent_GenderNeutral
        {
            get
            {
                return ResourceManager.GetString("Step parent (Gender neutral)", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Step child (Gender neutral).
        /// </summary>
        public static string FamilyRelationEnum_StepChild_GenderNeutral
        {
            get
            {
                return ResourceManager.GetString("Step child (Gender neutral)", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Step sibling (Gender neutral).
        /// </summary>
        public static string FamilyRelationEnum_StepSibling_GenderNeutral
        {
            get
            {
                return ResourceManager.GetString("Step sibling (Gender neutral)", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Family member (Gender neutral).
        /// </summary>
        public static string FamilyRelationEnum_FamilyMember_GenderNeutral
        {
            get
            {
                return ResourceManager.GetString("Family member (Gender neutral)", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Pet (Gender neutral).
        /// </summary>
        public static string FamilyRelationEnum_Pet_GenderNeutral
        {
            get
            {
                return ResourceManager.GetString("Pet (Gender neutral)", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Pet Owner (Gender neutral).
        /// </summary>
        public static string FamilyRelationEnum_PetOwner_GenderNeutral
        {
            get
            {
                return ResourceManager.GetString("Pet Owner (Gender neutral)", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Pdf.
        /// </summary>
        public static string AssetAsDocumentEnum_Pdf
        {
            get
            {
                return ResourceManager.GetString("Pdf", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Word.
        /// </summary>
        public static string AssetAsDocumentEnum_Word
        {
            get
            {
                return ResourceManager.GetString("Word", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to < 1 years old..
        /// </summary>
        public static string AgeCategoryEnum_Infancy
        {
            get
            {
                return ResourceManager.GetString("< 1 years old.", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to 1 - 3 years old..
        /// </summary>
        public static string AgeCategoryEnum_ToddlerYears
        {
            get
            {
                return ResourceManager.GetString("1 - 3 years old.", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to 4 - 8 years old..
        /// </summary>
        public static string AgeCategoryEnum_ChildHood
        {
            get
            {
                return ResourceManager.GetString("4 - 8 years old.", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to 9 - 13 years old..
        /// </summary>
        public static string AgeCategoryEnum_Puberty
        {
            get
            {
                return ResourceManager.GetString("9 - 13 years old.", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to 14 - 18 years old..
        /// </summary>
        public static string AgeCategoryEnum_OlderAdolescence
        {
            get
            {
                return ResourceManager.GetString("14 - 18 years old.", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to 19 - 30 years old..
        /// </summary>
        public static string AgeCategoryEnum_AdultHood
        {
            get
            {
                return ResourceManager.GetString("19 - 30 years old.", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to 31 - 50 years old..
        /// </summary>
        public static string AgeCategoryEnum_MiddleAge
        {
            get
            {
                return ResourceManager.GetString("31 - 50 years old.", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to > 50 years old..
        /// </summary>
        public static string AgeCategoryEnum_SeniorYears
        {
            get
            {
                return ResourceManager.GetString("> 50 years old.", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Airport.
        /// </summary>
        public static string AddressEnum_Airport
        {
            get
            {
                return ResourceManager.GetString("Airport", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Autonomous community.
        /// </summary>
        public static string AddressEnum_AutonomousCommunity
        {
            get
            {
                return ResourceManager.GetString("Autonomous community", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Borough.
        /// </summary>
        public static string AddressEnum_Borough
        {
            get
            {
                return ResourceManager.GetString("Borough", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Canton.
        /// </summary>
        public static string AddressEnum_Canton
        {
            get
            {
                return ResourceManager.GetString("Canton", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string AddressEnum_City
        {
            get
            {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to City region.
        /// </summary>
        public static string AddressEnum_CityRegion
        {
            get
            {
                return ResourceManager.GetString("City region", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Congressional district.
        /// </summary>
        public static string AddressEnum_CongressionalDistrict
        {
            get
            {
                return ResourceManager.GetString("Congressional district", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string AddressEnum_Country
        {
            get
            {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to County.
        /// </summary>
        public static string AddressEnum_County
        {
            get
            {
                return ResourceManager.GetString("County", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string AddressEnum_Department
        {
            get
            {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string AddressEnum_District
        {
            get
            {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Governorate.
        /// </summary>
        public static string AddressEnum_Governorate
        {
            get
            {
                return ResourceManager.GetString("Governorate", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Municipality.
        /// </summary>
        public static string AddressEnum_Municipality
        {
            get
            {
                return ResourceManager.GetString("Municipality", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to National park.
        /// </summary>
        public static string AddressEnum_NationalPark
        {
            get
            {
                return ResourceManager.GetString("National park", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Neighborhood.
        /// </summary>
        public static string AddressEnum_Neighborhood
        {
            get
            {
                return ResourceManager.GetString("Neighborhood", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Okrug.
        /// </summary>
        public static string AddressEnum_Okrug
        {
            get
            {
                return ResourceManager.GetString("Okrug", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Postal code.
        /// </summary>
        public static string AddressEnum_PostalCode
        {
            get
            {
                return ResourceManager.GetString("Postal code", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Prefecture.
        /// </summary>
        public static string AddressEnum_Prefecture
        {
            get
            {
                return ResourceManager.GetString("Prefecture", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string AddressEnum_Province
        {
            get
            {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string AddressEnum_Region
        {
            get
            {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string AddressEnum_State
        {
            get
            {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Territory.
        /// </summary>
        public static string AddressEnum_Territory
        {
            get
            {
                return ResourceManager.GetString("Territory", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Tv region.
        /// </summary>
        public static string AddressEnum_TvRegion
        {
            get
            {
                return ResourceManager.GetString("Tv region", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to Union territory.
        /// </summary>
        public static string AddressEnum_UnionTerritory
        {
            get
            {
                return ResourceManager.GetString("Union territory", resourceCulture);
            }
        }
                        
        /// <summary>
        ///   Looks up a localized string similar to University.
        /// </summary>
        public static string AddressEnum_University
        {
            get
            {
                return ResourceManager.GetString("University", resourceCulture);
            }
        }
                                    }
}