// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator
{
    internal sealed partial class Vsix
    {
        public const string Id = "CodeGenerator.52301bfa-9de5-4b61-bac8-0c05d4042e9f";
        public const string Name = "CodeGenerator";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Tane Kim";
        public const string Tags = "Generate, Code";
    }
}
