apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: app
spec:
  type: pubsub.natsstreaming
  version: v1
  metadata:
  - name: natsURL
    value: nats://stan:4222
  - name: natsStreamingClusterID
    value: appOnDapr
  - name: subscriptionType
    value: queue
