// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCodeGeneratorPackageString = "a5591d6b-dce0-4a42-bbf7-37a46fc72f47";
        public static Guid guidCodeGeneratorPackage = new Guid(guidCodeGeneratorPackageString);

        public const string guidValidFileString = "8baa355d-552b-4ddc-8308-c88bb8baffd7";
        public static Guid guidValidFile = new Guid(guidValidFileString);

        public const string guidCodeGeneratorPackageCmdSetString = "e7169fde-0aa9-40ce-95f1-4032a20c03da";
        public static Guid guidCodeGeneratorPackageCmdSet = new Guid(guidCodeGeneratorPackageCmdSetString);

        public const string guidEditorCommandsString = "160961b3-909d-4b28-9353-a1bef587b4a6";
        public static Guid guidEditorCommands = new Guid(guidEditorCommandsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int GenerateCodeId = 0x0100;
        public const int IDG_CTX_CODE = 0x0025;
    }
}