apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: oauth2
  namespace: default
spec:
  type: middleware.http.oauth2
  version: v1
  metadata:
  - name: clientId
    value: "code"
  - name: clientSecret
    value: "secret"
  - name: scopes
    value: "scp:address,scp:email,scp:phone,scp:profile,scp:roles"
  - name: authURL
    value: "https://localhost:5001/connect/authorize"
  - name: tokenURL
    value: "https://localhost:5001/connect/token"
  - name: redirectURL
    value: "https://localhost:3001/authentication/login-callback"
  - name: authHeaderName
    value: "JWT"
    # forceHTTPS:
    # This key is used to set HTTPS schema on redirect to your API method
    # after Dapr successfully received Access Token from Identity Provider.
    # By default, Dapr will use HTTP on this redirect.
  - name: forceHTTPS
    value: true