version: '3.7'

services:

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - '../app:/app'
      - '../app/node_modules'
    ports:
      - 3002:80
    environment:
      - CHOKIDAR_USEPOLLING=true