version: '3.7'

services:

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - 3002:3000
    environment:
      CHOKIDAR_USEPOLLING: 'true'
# volumes:
#   my-volume: